---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
#  - hub-bucket-secret.yaml

patches:
  - target:
      kind: AnsibleAutomationPlatform
      name: tntinfra
      namespace: aap
    patch: |-
      - op: replace
        path: /spec/hub/storage_type
        value: S3
      - op: replace
        path: /spec/hub/object_storage_s3_secret
        value: tntinfra-aap-s3
